TECH-1081 Update deprecated steps
Jahia/personal-api-tokens pull request #117
Opened 2023-01-16 16:40 UTC by Janin-Michel-Mathias

## JIRA

https://jira.jahia.org/browse/TECH-1081

## Description
Update deprecated steps

2023-01-17 10:11 UTC, dgriffon approved these changes

2023-01-17 10:16 UTC, dgriffon requested changes
Test and static analysis are failing, please make the PR green before merging

2023-01-31 14:35 UTC, Fgerthoffert approved these changes

2023-01-31 14:44 UTC, Fgerthoffert commented
The tests were fixed, static analysis will be updated during the next PR since these changes are completely unrelated with the actual module or tests codebas.

2023-01-31 14:44 UTC, merged